In [25]:
import pandas as pd

In [26]:
df = pd.read_excel("pnas.2103579118.sd04.xlsx", sheet_name="TTSs")
scores = pd.read_excel("pnas.2103579118.sd04.xlsx", sheet_name="folding", header=2)

df

,Locus tag,Old locus tag,Name,Type,Start,End,TTS,Location TTS
0,CDIF630_00001,CD630_00010,dnaA,gene,1.0,1320.0,1457,3UTR
1,CDIF630_00002,CD630_00020,dnaN,gene,1562.0,2668.0,2730,3UTR
2,CDIF630_00006,CD630_00060,gyrA,gene,6066.0,8492.0,8516,3UTR
3,CDIF630_00011,CD630_00110,sigB,gene,9857.0,10630.0,10749,3UTR
4,CDIF630_00012,NaN,CDIF630_00012,gene,10821.0,12311.0,12344,3UTR
...,...,...,...,...,...,...,...,...
2037,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3381303,CRISPR
2038,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3381600,CRISPR
2039,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3382125,CRISPR
2040,orphan,NaN,NaN,NaN,NaN,NaN,3616893,orphan
2041,orphan,NaN,NaN,NaN,NaN,NaN,4066749,3UTR

In [27]:
scores

,TTS Position,Sequence,Secondary Structure,Folding energy (kcal/mol)
0,3129623,GAAUAAAAAGUAUUAAAAAAAAUAUUAUUUGUUUUGAGACAUUUUA...,((((((((.((.((((((.((((...)))).)))))).)).)))))...,-9.9
1,3150200,UGUGCUUUUAAAUAAAUACUCAAUACGUAUUUGUAGAGUUUAAGUA...,(((((((....((((((((.......)))))))).......)))))...,-9.9
2,3921140,GUAAGUAUAAUUAAAUAGAUUUGGUUUUCUAGAGAACCCUUUUUAG...,(((.(((.(((((((.((....((((((....)))))))).)))))...,-9.9
3,723733,UCUUAUUUAUUAUAGGAUUUUGUUAUAUUACAAUCUCUUAUUUAUU...,...........((((((..((((......))))..)))))).((((...,-9.8
4,1096107,ACUUCUAAAAAUUGCAUGUGACAAGAUAAAAGCAGUACAGUUAGAU...,...(((((..(((((.(((......)))...)))))....)))))....,-9.8
...,...,...,...,...
2005,2339206,CUAUCCAAUAAUUUUCCAAUUACUGUCCUUAUGAAAUAUCAAUUUA...,..(((..((((............((((..((((((.......))))...,-1.7
2006,2699808,UUAUAAUUGUAUACAUUUAAAUCUAAAUAUUAUUAUACUGAUACUU...,...........................((((((((..............,-1.7
2007,10749,UGAAAAAAGGAACAAGAAAUAAACACGAACAUUGAAAAUUAAACAG...,...................................((((((..(.....,-1.5
2008,3675913,UAUAUCCGUAGUAUAAAAUAUAUAUGUAUACCAAAUUUUAUCAAAA...,.......((((((............(((((...(((((...........,-1.3
2009,2645167,AAUAUAUAACUAUAUAAAAAAUAAUAUCUUAUAAAUAAUAAGCCUA...,...........................(((((.....))))).......,-0.7

In [28]:
#  add the "Folding energy(kcal/mol)" column from the scores dataframe to df dataframe based on the TTS Position column of scores to TTS of df
df_1 = df.merge(scores, right_on="TTS Position", left_on="TTS")
df_1

,Locus tag,Old locus tag,Name,Type,Start,End,TTS,Location TTS,TTS Position,Sequence,Secondary Structure,Folding energy (kcal/mol)
0,CDIF630_00001,CD630_00010,dnaA,gene,1.0,1320.0,1457,3UTR,1457,UCAAGUCUAAAAUAACAAAGAUAUUAACAUCUUAUACACAUGUUAA...,.........(((((.(((((((((((((((.........)))))))...,-17.2
1,CDIF630_00002,CD630_00020,dnaN,gene,1562.0,2668.0,2730,3UTR,2730,GACAUGAAGGAGUUGUCUUUUGUAGAAAAUUUUUCUAAUCUUAGAC...,.....(((((((((((((....((((((...)))))).....))))...,-22.9
2,CDIF630_00006,CD630_00060,gyrA,gene,6066.0,8492.0,8516,3UTR,8516,GUUUCGAUUGCCAAAAUAAAUAUUGAAGAAGAAUAGGAUAAAUAUC...,((((.((((((.........(((..((((((((((((((....)))...,-17.0
3,CDIF630_00011,CD630_00110,sigB,gene,9857.0,10630.0,10749,3UTR,10749,UGAAAAAAGGAACAAGAAAUAAACACGAACAUUGAAAAUUAAACAG...,...................................((((((..(.....,-1.5
4,CDIF630_00012,NaN,CDIF630_00012,gene,10821.0,12311.0,12344,3UTR,12344,GUAUCGGAAGGUGCGGCUGGAUCACCUCCUUUCUAAGGAGAAUUAC...,...((((((...((((..((.....((((((...)))))).....)...,-18.6
...,...,...,...,...,...,...,...,...,...,...,...,...
2037,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3381303,CRISPR,3381303,AUGUGGACUUAAAAUUAAAAAUAAUUCAAAAACACUUACAAAUGAG...,.(((.(.(((...((((((((.........(((((((((......)...,-13.6
2038,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3381600,CRISPR,3381600,AGAGAAUAAAUAAUAUAGAUAAAGCACUUGGAUAUUGUAUAGUUUC...,..............((((((((((((((((((..(.....)..)))...,-23.6
2039,CRISPR 15/16,NaN,NaN,NaN,NaN,NaN,3382125,CRISPR,3382125,GUGUAUGUGUAGAUAUUGGAAAUACUAAGUUUAUUUUGGGGUUUUA...,..................(((((.(((((.....))))).)))))(...,-9.0
2040,orphan,NaN,NaN,NaN,NaN,NaN,3616893,orphan,3616893,GAUAUAAUGCACUAAAAAAAGGAUGUUAUCUUUUUUAUUAAAAUAU...,.(((((((((..........(((((((((.((((.....)))).))...,-14.9
2041,orphan,NaN,NaN,NaN,NaN,NaN,4066749,3UTR,4066749,UAAAAAAACCUCCUCUUUUGUUUAUAUUAAGAAUUGUAACAAAGAG...,.(((((((.(((((((((.(((.(((........))))))))))))...,-15.6

In [29]:
# convert 'NaN' to Nan
df_1 = df_1.replace('NaN', pd.NA)

In [33]:
df_1 = df_1[(df_1["Locus tag"] != "orphan")  & (df_1["Type"] == "gene") & (df_1["Location TTS"] == "3UTR")]
df_1

,Locus tag,Old locus tag,Name,Type,Start,End,TTS,Location TTS,TTS Position,Sequence,Secondary Structure,Folding energy (kcal/mol)
0,CDIF630_00001,CD630_00010,dnaA,gene,1.0,1320.0,1457,3UTR,1457,UCAAGUCUAAAAUAACAAAGAUAUUAACAUCUUAUACACAUGUUAA...,.........(((((.(((((((((((((((.........)))))))...,-17.2
1,CDIF630_00002,CD630_00020,dnaN,gene,1562.0,2668.0,2730,3UTR,2730,GACAUGAAGGAGUUGUCUUUUGUAGAAAAUUUUUCUAAUCUUAGAC...,.....(((((((((((((....((((((...)))))).....))))...,-22.9
2,CDIF630_00006,CD630_00060,gyrA,gene,6066.0,8492.0,8516,3UTR,8516,GUUUCGAUUGCCAAAAUAAAUAUUGAAGAAGAAUAGGAUAAAUAUC...,((((.((((((.........(((..((((((((((((((....)))...,-17.0
3,CDIF630_00011,CD630_00110,sigB,gene,9857.0,10630.0,10749,3UTR,10749,UGAAAAAAGGAACAAGAAAUAAACACGAACAUUGAAAAUUAAACAG...,...................................((((((..(.....,-1.5
4,CDIF630_00012,NaN,CDIF630_00012,gene,10821.0,12311.0,12344,3UTR,12344,GUAUCGGAAGGUGCGGCUGGAUCACCUCCUUUCUAAGGAGAAUUAC...,...((((((...((((..((.....((((((...)))))).....)...,-18.6
...,...,...,...,...,...,...,...,...,...,...,...,...
2000,CDIF630_03998,CD630_36690,CDIF630_03998,gene,4263148.0,4263723.0,4263777,3UTR,4263777,AAGUAAUUUCUUGAAACUAUUAUCAAAUAGAUUAGAGGUUCUUAGG...,.....(((((((...........((((.(((..((.(((((....)...,-16.3
2001,CDIF630_03999,CD630_36700,sufS2,gene,4263857.0,4264999.0,4263783,3UTR,4263783,AAUAUAGAAAUAAAAAAAGGGGAUAUUUCAAAAUAAAAAUUUGAAU...,............((((((((((((..((((((.......))))))....,-17.4
2002,CDIF630_04002,CD630_36730,noc,gene,4266805.0,4267590.0,4266775,3UTR,4266775,GGAAGUUGUUGUAAAAAUCCCUAAAAAAUAGAGAUUACUGCUUACC...,((....(((((((((((.............((((((((((.....)...,-14.8
2005,CDIF630_04007,CD630_36770,jag,gene,4271945.0,4272574.0,4271911,3UTR,4271911,AGAUUAGUAAUUGAGUGUAAAAGAUAAAGUCAACCUCCUAAACAUU...,.((((((((((......(((((((((((....(((((((((...))...,-20.3
2006,CDIF630_04011,CD630_36800,rpmH,gene,4273987.0,4274124.0,4273950,3UTR,4273950,GGAAGAAAUAGAUUAACUCAUUAAUUACAAAAGGGCCGCUGCAAAG...,..........((((((....))))))((((((((((((((.....)...,-22.3

In [34]:
df_1.drop(columns=["Old locus tag", "Name", "Type", "Start", "End", "Location TTS", "TTS Position", "Sequence", "Secondary Structure"], inplace=True)
df_1

/tmp/ipykernel_19163/514471772.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1.drop(columns=["Old locus tag", "Name", "Type", "Start", "End", "Location TTS", "TTS Position", "Sequence", "Secondary Structure"], inplace=True)

          Locus tag      TTS  Folding energy (kcal/mol)
0     CDIF630_00001     1457                      -17.2
1     CDIF630_00002     2730                      -22.9
2     CDIF630_00006     8516                      -17.0
3     CDIF630_00011    10749                       -1.5
4     CDIF630_00012    12344                      -18.6
...             ...      ...                        ...
2000  CDIF630_03998  4263777                      -16.3
2001  CDIF630_03999  4263783                      -17.4
2002  CDIF630_04002  4266775                      -14.8
2005  CDIF630_04007  4271911                      -20.3
2006  CDIF630_04011  4273950                      -22.3

[1646 rows x 3 columns]

In [36]:
# chromosome, start, end, Associated gene , score, strand
df_1['gene'] = [f"CP010905.2_{i}" for i in range(len(df_1))]
df_1["start"] = df_1["TTS"] - 1
df_1["end"] = df_1["TTS"]
df_1.drop(columns=["TTS"], inplace=True)
df_1

/tmp/ipykernel_19163/93664814.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['gene'] = [f"CP010905.2_{i}" for i in range(len(df_1))]
/tmp/ipykernel_19163/93664814.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1["start"] = df_1["TTS"] - 1
/tmp/ipykernel_19163/93664814.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1["end"] = df_1["TTS"]
/tmp/ipykernel_19163/93664814.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1.drop(columns=["TTS"], inplace=True)

,Locus tag,Folding energy (kcal/mol),gene,start,end
0,CDIF630_00001,-17.2,CP010905.2_0,1456,1457
1,CDIF630_00002,-22.9,CP010905.2_1,2729,2730
2,CDIF630_00006,-17.0,CP010905.2_2,8515,8516
3,CDIF630_00011,-1.5,CP010905.2_3,10748,10749
4,CDIF630_00012,-18.6,CP010905.2_4,12343,12344
...,...,...,...,...,...
2000,CDIF630_03998,-16.3,CP010905.2_1641,4263776,4263777
2001,CDIF630_03999,-17.4,CP010905.2_1642,4263782,4263783
2002,CDIF630_04002,-14.8,CP010905.2_1643,4266774,4266775
2005,CDIF630_04007,-20.3,CP010905.2_1644,4271910,4271911
2006,CDIF630_04011,-22.3,CP010905.2_1645,4273949,4273950

# Adding strand from gene annotation

In [37]:
# read sequence.txt file and save the lines that have "complement" in them in a list
with open("sequence.txt", "r") as f:
    lines = f.readlines()
    lines = [line.strip() for line in lines if "complement" in line]

In [38]:

# extract the locus tag of the complement regions
locus = [line.split("locus_tag=")[1].split("]")[0] for line in lines]
print(locus[1:10])

['CDIF630_00093', 'CDIF630_00203', 'CDIF630_00245', 'CDIF630_00276', 'CDIF630_00286', 'CDIF630_00287', 'CDIF630_00288', 'CDIF630_00290', 'CDIF630_00291']

In [39]:
df_1["strand"] = df_1.apply(lambda x: "+" if x["Locus tag"] not in locus else "-", axis=1)

/tmp/ipykernel_19163/769491347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1["strand"] = df_1.apply(lambda x: "+" if x["Locus tag"] not in locus else "-", axis=1)

In [40]:

df_1.head(20)

,Locus tag,Folding energy (kcal/mol),gene,start,end,strand
0,CDIF630_00001,-17.2,CP010905.2_0,1456,1457,+
1,CDIF630_00002,-22.9,CP010905.2_1,2729,2730,+
2,CDIF630_00006,-17.0,CP010905.2_2,8515,8516,+
3,CDIF630_00011,-1.5,CP010905.2_3,10748,10749,+
4,CDIF630_00012,-18.6,CP010905.2_4,12343,12344,+
5,CDIF630_00013,-17.4,CP010905.2_5,15498,15499,+
6,CDIF630_00014,-22.8,CP010905.2_6,15817,15818,+
7,CDIF630_00015,-25.8,CP010905.2_7,15911,15912,+
8,CDIF630_00018,-18.6,CP010905.2_8,17742,17743,+
9,CDIF630_00019,-16.9,CP010905.2_9,21014,21015,+
10,CDIF630_00020,-13.1,CP010905.2_10,21259,21260,+
12,CDIF630_00024,-19.4,CP010905.2_11,24632,24633,+
13,CDIF630_00026,-12.3,CP010905.2_12,25390,25391,+
14,CDIF630_00028,-8.8,CP010905.2_13,25693,25694,+
15,CDIF630_00032,-23.8,CP010905.2_14,28453,28454,+
16,CDIF630_00033,-15.3,CP010905.2_15,28850,28851,+
17,CDIF630_00034,-16.8,CP010905.2_16,28801,28802,-
18,CDIF630_00035,-17.7,CP010905.2_17,32092,32093,+
19,CDIF630_00036,-17.4,CP010905.2_18,35226,35227,+
20,CDIF630_00037,-18.4,CP010905.2_19,35525,35526,+

In [42]:
df_1 = df_1[["gene", "start", "end", "Locus tag", "Folding energy (kcal/mol)", "strand"]]
df_1

,gene,start,end,Locus tag,Folding energy (kcal/mol),strand
0,CP010905.2_0,1456,1457,CDIF630_00001,-17.2,+
1,CP010905.2_1,2729,2730,CDIF630_00002,-22.9,+
2,CP010905.2_2,8515,8516,CDIF630_00006,-17.0,+
3,CP010905.2_3,10748,10749,CDIF630_00011,-1.5,+
4,CP010905.2_4,12343,12344,CDIF630_00012,-18.6,+
...,...,...,...,...,...,...
2000,CP010905.2_1641,4263776,4263777,CDIF630_03998,-16.3,+
2001,CP010905.2_1642,4263782,4263783,CDIF630_03999,-17.4,-
2002,CP010905.2_1643,4266774,4266775,CDIF630_04002,-14.8,-
2005,CP010905.2_1644,4271910,4271911,CDIF630_04007,-20.3,-
2006,CP010905.2_1645,4273949,4273950,CDIF630_04011,-22.3,-

In [18]:
df_1.to_csv("ClostridioidesDifficile_630_CP010905.2.bed", sep='\t', header=False, index=False)