In [80]:
import pandas as pd

In [81]:
lb4 = pd.read_excel("elife-62438-supp1_.xlsx", sheet_name= "LB 0.4", header = 1)
lb2 = pd.read_excel("elife-62438-supp1_.xlsx", sheet_name= "LB 2.0", header = 1)
m63 = pd.read_excel("elife-62438-supp1_.xlsx", sheet_name= "M63 0.4", header = 1)

In [82]:
lb4

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,256,+,4852.3250,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",CCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGG...
1,9230,+,16185.7000,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
2,9920,+,1107.0320,"primary, antisense,","P:gene_id ""EG11511""; gene_name ""mog"";,A:gene_i...",GCAAGACGCGACGTTAGCGAATAAAAAAATCCCCCCGAGCGGGGGG...
3,10394,-,23469.0000,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";",CGGCATGACCACCATTCTGCTTAACCTGCACAACGTGGGTTATTTC...
4,14145,+,1862.0500,"internal,","I:gene_id ""G0-8893""; gene_name ""tpke11"";",GTAATTATACTGACACGGGCGAAGGGGAATTTCCTCTCCGCCCGTG...
...,...,...,...,...,...,...
1170,4606792,+,1344.5560,"antisense,","A:gene_id ""G7950""; gene_name ""rsmC"";",TGGAAGCCAAATGTCTCATCCAGCACGTCCGGATAAGGCAGGAAGG...
1171,4621665,+,869.5075,orphan,NaN,GCAAGGCGATTGCCTTGTGAAGCCGGAGCGGGAGACTGCTCCGGCT...
1172,4635102,-,80404.7500,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",TATTCGTGCTCGTCGTTTGTCGAAATCGGCGGTCGCACTACGCCTG...
1173,4640124,-,23469.0000,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",GAATATGACATCAACCTGGTGATCATGGATATCAATCTGCCGGGTA...
1174,4640397,-,50666.0000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",CGTTGATGGAAAGTGCATCAAGAACGCAATTACGTACTTTAGTCAT...

In [83]:
m63

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,267,+,11296.1700,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",ACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTAC...
1,3860,+,889.9750,"internal,","I:gene_id ""EG11000""; gene_name ""thrC"";",ATCAGGGGCTGTTTTTTCCGCACGACCTGCCGGAATTCAGCCTGAC...
2,9230,+,5361.7750,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
3,17007,+,165203.0000,"primary, antisense,","P:gene_id ""G0-9581""; gene_name ""sokC"";,A:gene_...",GCATATAGGAGGCCTCGGGTTGATGGTAAAATATCACTCGGGGCTT...
4,17501,+,1092.6550,"internal,","I:gene_id ""EG10652""; gene_name ""nhaA"";",AGTAAAAACGATCTATTCACCTGAAAGAGAAATAAAAAGTGAAACA...
...,...,...,...,...,...,...
1048,4611232,+,2123.5950,orphan,NaN,CGTTCAATGCGTAGATATCAGTATCTAAAGCCGTCGATTGTCATTC...
1049,4612043,+,1171.9070,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",ACTAAGTAATTCGTCGTAATTCGTCCTCCCGAACTTTGTCGGGAGG...
1050,4612345,+,1378.9705,orphan,NaN,AGACCATTAAGAAAATTTTATCCAAAGCCAGTCCAGCGGACTGGCT...
1051,4635102,-,81198.0000,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",TATTCGTGCTCGTCGTTTGTCGAAATCGGCGGTCGCACTACGCCTG...
1052,4640415,-,45026.4000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",AGCTAATGATGTTGTTGACGTTGATGGAAAGTGCATCAAGAACGCA...

In [84]:
lb2

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,267,+,4108.370,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",ACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTAC...
1,9230,+,5585.590,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
2,10394,-,40653.650,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";",CGGCATGACCACCATTCTGCTTAACCTGCACAACGTGGGTTATTTC...
3,17007,+,36222.800,"primary, antisense,","P:gene_id ""G0-9581""; gene_name ""sokC"";,A:gene_...",GCATATAGGAGGCCTCGGGTTGATGGTAAAATATCACTCGGGGCTT...
4,17504,+,3078.490,"internal,","I:gene_id ""EG10652""; gene_name ""nhaA"";",AAAAACGATCTATTCACCTGAAAGAGAAATAAAAAGTGAAACATCT...
...,...,...,...,...,...,...
877,4612044,+,2252.085,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",CTAAGTAATTCGTCGTAATTCGTCCTCCCGAACTTTGTCGGGAGGC...
878,4612345,+,1397.795,orphan,NaN,AGACCATTAAGAAAATTTTATCCAAAGCCAGTCCAGCGGACTGGCT...
879,4635102,-,108833.950,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",TATTCGTGCTCGTCGTTTGTCGAAATCGGCGGTCGCACTACGCCTG...
880,4640223,-,40273.350,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",GAGTTGGTAACACGCAACACGTTGAAAAGTATTTTCGAAGCGGAAG...
881,4640415,-,231175.000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",AGCTAATGATGTTGTTGACGTTGATGGAAAGTGCATCAAGAACGCA...

In [85]:
# append all of the dataframes into one big and merge them on the first column as index
df = pd.concat([lb4, lb2, m63], axis=0, ignore_index=True)

In [86]:
df

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,256,+,4852.3250,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",CCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGG...
1,9230,+,16185.7000,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
2,9920,+,1107.0320,"primary, antisense,","P:gene_id ""EG11511""; gene_name ""mog"";,A:gene_i...",GCAAGACGCGACGTTAGCGAATAAAAAAATCCCCCCGAGCGGGGGG...
3,10394,-,23469.0000,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";",CGGCATGACCACCATTCTGCTTAACCTGCACAACGTGGGTTATTTC...
4,14145,+,1862.0500,"internal,","I:gene_id ""G0-8893""; gene_name ""tpke11"";",GTAATTATACTGACACGGGCGAAGGGGAATTTCCTCTCCGCCCGTG...
...,...,...,...,...,...,...
3105,4611232,+,2123.5950,orphan,NaN,CGTTCAATGCGTAGATATCAGTATCTAAAGCCGTCGATTGTCATTC...
3106,4612043,+,1171.9070,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",ACTAAGTAATTCGTCGTAATTCGTCCTCCCGAACTTTGTCGGGAGG...
3107,4612345,+,1378.9705,orphan,NaN,AGACCATTAAGAAAATTTTATCCAAAGCCAGTCCAGCGGACTGGCT...
3108,4635102,-,81198.0000,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",TATTCGTGCTCGTCGTTTGTCGAAATCGGCGGTCGCACTACGCCTG...
3109,4640415,-,45026.4000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",AGCTAATGATGTTGTTGACGTTGATGGAAAGTGCATCAAGAACGCA...

In [87]:
# select the row that have unique values of the first column
df = df.drop_duplicates(subset=['3´ end position'])

In [88]:
df

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,256,+,4852.3250,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",CCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGG...
1,9230,+,16185.7000,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
2,9920,+,1107.0320,"primary, antisense,","P:gene_id ""EG11511""; gene_name ""mog"";,A:gene_i...",GCAAGACGCGACGTTAGCGAATAAAAAAATCCCCCCGAGCGGGGGG...
3,10394,-,23469.0000,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";",CGGCATGACCACCATTCTGCTTAACCTGCACAACGTGGGTTATTTC...
4,14145,+,1862.0500,"internal,","I:gene_id ""G0-8893""; gene_name ""tpke11"";",GTAATTATACTGACACGGGCGAAGGGGAATTTCCTCTCCGCCCGTG...
...,...,...,...,...,...,...
3096,4546083,+,828.2595,"internal,","I:gene_id ""EG10311""; gene_name ""fimD"";",TTAAACAAAATGGGTATGACATTTATAATAGTACGGTGCCACCGGG...
3098,4604742,-,87413.4500,"antisense,","A:gene_id ""G7948""; gene_name ""bglJ"";",TAACAGAATATCTGCGGCCTCCAACAACCCTGCGTCAGAACTGACG...
3099,4605576,-,118498.7500,"internal,","I:gene_id ""G7949""; gene_name ""fhuF"";",TCTGGCGAACGCATCTCCAGCCGCAGGATCCCACGCTTGCGCAAGC...
3100,4605858,+,3238.1750,"internal,","I:gene_id ""G0-10474""; gene_name ""yjjZ"";",TGCAACGTACGCTGGGCAGTGGCTGGGGAGTGTTGCTGCCGGGATT...
3106,4612043,+,1171.9070,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",ACTAAGTAATTCGTCGTAATTCGTCCTCCCGAACTTTGTCGGGAGG...

In [89]:
# sort the dataframe by the first column
df = df.sort_values(by=['3´ end position'] , ascending=True)
# reset the index
df = df.reset_index(drop=True)

In [90]:
df

,3´ end position,strand,Term-seq AVG read count,classification,details,3′ end region
0,256,+,4852.325,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",CCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGG...
1,267,+,4108.370,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",ACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTAC...
2,3860,+,889.975,"internal,","I:gene_id ""EG11000""; gene_name ""thrC"";",ATCAGGGGCTGTTTTTTCCGCACGACCTGCCGGAATTCAGCCTGAC...
3,9230,+,16185.700,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",GATCTGCTGTAATCATTCTTAGCGTGACCGGGAAGTCGGTCACGCT...
4,9920,+,1107.032,"primary, antisense,","P:gene_id ""EG11511""; gene_name ""mog"";,A:gene_i...",GCAAGACGCGACGTTAGCGAATAAAAAAATCCCCCCGAGCGGGGGG...
...,...,...,...,...,...,...
2068,4635102,-,80404.750,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",TATTCGTGCTCGTCGTTTGTCGAAATCGGCGGTCGCACTACGCCTG...
2069,4640124,-,23469.000,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",GAATATGACATCAACCTGGTGATCATGGATATCAATCTGCCGGGTA...
2070,4640223,-,40273.350,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",GAGTTGGTAACACGCAACACGTTGAAAAGTATTTTCGAAGCGGAAG...
2071,4640397,-,50666.000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",CGTTGATGGAAAGTGCATCAAGAACGCAATTACGTACTTTAGTCAT...
2072,4640415,-,231175.000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";",AGCTAATGATGTTGTTGACGTTGATGGAAAGTGCATCAAGAACGCA...

In [91]:
df['classification'].value_counts()

internal,                824
orphan                   516
primary,                 302
antisense,               228
primary, antisense,      166
internal, antisense,      19
primary, internal,        18
Name: classification, dtype: int64

In [92]:
df.drop(["3′ end region",], axis = 1, inplace = True)
df

,3´ end position,strand,Term-seq AVG read count,classification,details
0,256,+,4852.325,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";"
1,267,+,4108.370,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";"
2,3860,+,889.975,"internal,","I:gene_id ""EG11000""; gene_name ""thrC"";"
3,9230,+,16185.700,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";"
4,9920,+,1107.032,"primary, antisense,","P:gene_id ""EG11511""; gene_name ""mog"";,A:gene_i..."
...,...,...,...,...,...
2068,4635102,-,80404.750,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";"
2069,4640124,-,23469.000,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";"
2070,4640223,-,40273.350,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";"
2071,4640397,-,50666.000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";"
2072,4640415,-,231175.000,"antisense,","A:gene_id ""G7954""; gene_name ""yjjY"";"

In [93]:
# if the value in the classification column has orphan or antisense, then drop the row.
df = df[~df['classification'].isin(['orphan', 'antisense, ', 'primary, antisense, ', 'internal, antisense, '])]
df

,3´ end position,strand,Term-seq AVG read count,classification,details
0,256,+,4852.325,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";"
1,267,+,4108.370,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";"
2,3860,+,889.975,"internal,","I:gene_id ""EG11000""; gene_name ""thrC"";"
3,9230,+,16185.700,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";"
5,10394,-,23469.000,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";"
...,...,...,...,...,...
2064,4612043,+,1171.907,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";"
2065,4612044,+,2252.085,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";"
2068,4635102,-,80404.750,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";"
2069,4640124,-,23469.000,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";"
2070,4640223,-,40273.350,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";"

In [94]:
2017 - 516 - 228 - 166

1107

In [95]:
df['classification'].value_counts()

internal,              824
primary,               302
primary, internal,      18
Name: classification, dtype: int64

In [96]:
df["gene"] = ["NC_000913.3" + "_{}".format(j) for j in range(len(df))]
df

/tmp/ipykernel_42779/3802968094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gene"] = ["NC_000913.3" + "_{}".format(j) for j in range(len(df))]

,3´ end position,strand,Term-seq AVG read count,classification,details,gene
0,256,+,4852.325,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",NC_000913.3_0
1,267,+,4108.370,"primary,","P:gene_id ""EG11277""; gene_name ""thrL"";",NC_000913.3_1
2,3860,+,889.975,"internal,","I:gene_id ""EG11000""; gene_name ""thrC"";",NC_000913.3_2
3,9230,+,16185.700,"primary,","P:gene_id ""EG11556""; gene_name ""talB"";",NC_000913.3_3
5,10394,-,23469.000,"internal,","I:gene_id ""EG11512""; gene_name ""satP"";",NC_000913.3_4
...,...,...,...,...,...,...
2064,4612043,+,1171.907,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",NC_000913.3_1139
2065,4612044,+,2252.085,"primary,","P:gene_id ""EG11391""; gene_name ""osmY"";",NC_000913.3_1140
2068,4635102,-,80404.750,"internal,","I:gene_id ""EG11366""; gene_name ""rob"";",NC_000913.3_1141
2069,4640124,-,23469.000,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",NC_000913.3_1142
2070,4640223,-,40273.350,"internal,","I:gene_id ""EG10061""; gene_name ""arcA"";",NC_000913.3_1143

In [98]:
df["name"] = df["details"] + " | " + df["classification"]

/tmp/ipykernel_42779/618743268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["name"] = df["details"] + " | " + df["classification"]

In [99]:

df.drop(["details", "classification"], axis = 1, inplace = True)
df

/tmp/ipykernel_42779/1791481997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["details", "classification"], axis = 1, inplace = True)

,3´ end position,strand,Term-seq AVG read count,gene,name
0,256,+,4852.325,NC_000913.3_0,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima..."
1,267,+,4108.370,NC_000913.3_1,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima..."
2,3860,+,889.975,NC_000913.3_2,"I:gene_id ""EG11000""; gene_name ""thrC""; | inter..."
3,9230,+,16185.700,NC_000913.3_3,"P:gene_id ""EG11556""; gene_name ""talB""; | prima..."
5,10394,-,23469.000,NC_000913.3_4,"I:gene_id ""EG11512""; gene_name ""satP""; | inter..."
...,...,...,...,...,...
2064,4612043,+,1171.907,NC_000913.3_1139,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima..."
2065,4612044,+,2252.085,NC_000913.3_1140,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima..."
2068,4635102,-,80404.750,NC_000913.3_1141,"I:gene_id ""EG11366""; gene_name ""rob""; | intern..."
2069,4640124,-,23469.000,NC_000913.3_1142,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter..."
2070,4640223,-,40273.350,NC_000913.3_1143,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter..."

In [100]:
df['start'] = df['3´ end position'] - 1
df['end'] = df['3´ end position']

df.drop(["3´ end position"], axis = 1, inplace = True)

df

/tmp/ipykernel_42779/2645492700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start'] = df['3´ end position'] - 1
/tmp/ipykernel_42779/2645492700.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['end'] = df['3´ end position']
/tmp/ipykernel_42779/2645492700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["3´ end position"], axis = 1, inplace = True)

,strand,Term-seq AVG read count,gene,name,start,end
0,+,4852.325,NC_000913.3_0,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima...",255,256
1,+,4108.370,NC_000913.3_1,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima...",266,267
2,+,889.975,NC_000913.3_2,"I:gene_id ""EG11000""; gene_name ""thrC""; | inter...",3859,3860
3,+,16185.700,NC_000913.3_3,"P:gene_id ""EG11556""; gene_name ""talB""; | prima...",9229,9230
5,-,23469.000,NC_000913.3_4,"I:gene_id ""EG11512""; gene_name ""satP""; | inter...",10393,10394
...,...,...,...,...,...,...
2064,+,1171.907,NC_000913.3_1139,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima...",4612042,4612043
2065,+,2252.085,NC_000913.3_1140,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima...",4612043,4612044
2068,-,80404.750,NC_000913.3_1141,"I:gene_id ""EG11366""; gene_name ""rob""; | intern...",4635101,4635102
2069,-,23469.000,NC_000913.3_1142,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter...",4640123,4640124
2070,-,40273.350,NC_000913.3_1143,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter...",4640222,4640223

In [101]:

df = df[["gene", "start", "end", "name", "Term-seq AVG read count", "strand"]]
df

,gene,start,end,name,Term-seq AVG read count,strand
0,NC_000913.3_0,255,256,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima...",4852.325,+
1,NC_000913.3_1,266,267,"P:gene_id ""EG11277""; gene_name ""thrL""; | prima...",4108.370,+
2,NC_000913.3_2,3859,3860,"I:gene_id ""EG11000""; gene_name ""thrC""; | inter...",889.975,+
3,NC_000913.3_3,9229,9230,"P:gene_id ""EG11556""; gene_name ""talB""; | prima...",16185.700,+
5,NC_000913.3_4,10393,10394,"I:gene_id ""EG11512""; gene_name ""satP""; | inter...",23469.000,-
...,...,...,...,...,...,...
2064,NC_000913.3_1139,4612042,4612043,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima...",1171.907,+
2065,NC_000913.3_1140,4612043,4612044,"P:gene_id ""EG11391""; gene_name ""osmY""; | prima...",2252.085,+
2068,NC_000913.3_1141,4635101,4635102,"I:gene_id ""EG11366""; gene_name ""rob""; | intern...",80404.750,-
2069,NC_000913.3_1142,4640123,4640124,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter...",23469.000,-
2070,NC_000913.3_1143,4640222,4640223,"I:gene_id ""EG10061""; gene_name ""arcA""; | inter...",40273.350,-

In [102]:
# convert df to bed file format
# {FullNameOfTheBacteria}_{strainCode}_{GenomeAccessionNumber}.bed    
df.to_csv('EscherichiaColi_K12-MG1655_NC000913.3.bed', sep='\t', index=False, header=False)